#!/usr/bin/env python3

import sys
import subprocess
import argparse
from pathlib import Path
import struct
import re
from shutil import rmtree, copy
import os
import time
import hashlib

def cleanup(game_dir_patched):
    if game_dir_patched.exists():
        eldenring_path = game_dir_patched / "eldenring.exe"
        while eldenring_path.exists():
            try:
                os.remove(eldenring_path)
                break
            except PermissionError:
                # eldenring.exe is still running, retry in 3 s
                time.sleep(3)
            except Exception as e:
                print(f"er-patcher: could not delete {eldenring_path}: {e}")
                break
        rmtree(game_dir_patched)

if __name__ == "__main__":
    if "--" in sys.argv:
        patcher_args = sys.argv[1:sys.argv.index('--')]
    else:
        patcher_args = sys.argv[1:]


    parser = argparse.ArgumentParser(description="Patch Elden Ring executable and launch it without EAC.")

    parser.add_argument("-x", "--executable", action='store', type=str, default="eldenring.exe", help="The executable to launch, relative to the games folder.")
    parser.add_argument("--with-eac", action='store_true', help="Run game with EAC (Use at own your risk)")
    parser.add_argument("--all", action='store_true', help="Enable all options except --rate, --executable, --no-rotate-camera, --player-camera, --increase-animation-distance and gameplay changes like --disable-rune-loss.")
    parser.add_argument("-p", "--permanent", action='store_true', help="Make the patches permanent.")
    parser.add_argument("-g", "--gamepath", action='store', type=str, default=".", help="Path to game.")

    parser.add_argument("-r", "--rate", type=int, default=60, help="Modify the frame rate limit (e.g. 30, 120, 165 or whatever).")
    parser.add_argument("--disable-rune-loss", action='store_true', help="Disable losing runes upon death.")
    parser.add_argument("-u", "--ultrawide", action='store_true', help="Removes black bars when using a resolution with an aspect ratio other than 16:9.")
    parser.add_argument("-v", "--disable-vignette", action='store_true', help="Disables the vignette overlay.")
    parser.add_argument("-c", "--disable-ca", action='store_true', help="Disables chromatic abberation.")
    parser.add_argument("-a", "--increase-animation-distance", action='store_true', help="Increase animation distance.")
    parser.add_argument("-s", "--skip-intro", action='store_true', help="Skip intro logos.")
    parser.add_argument("-f", "--remove-60hz-fullscreen", action='store_true', help="Remove 60hz lock in fullscreen.")
    parser.add_argument("-q", "--quick-respawn", action='store_true', help="Respawn a few seconds faster.")
    parser.add_argument("-e", "--player-camera", action='store_true', help="Always center camera to player.")
    parser.add_argument("-y", "--fix-camera", action='store_true', help="Disable camera reset.")
    parser.add_argument("-b", "--no-rotate-camera", action='store_true', help="Disable camera auto rotate.")

    patches = parser.parse_args(patcher_args)

    if "--" in sys.argv and not patches.permanent:
        patcher_args = sys.argv[1:sys.argv.index("--")]
    elif "--" in sys.argv and patches.permanent:
        print(f"\033[91mpermanent patch cannot be combined with temporary patches. Remove -p | --permanent or {sys.argv[sys.argv.index('--'):]}\033[m")
    elif "--" not in sys.argv and patches.permanent:
        pass
    else:
        exit("\033[91mYou did not specify if the patch is temporary or permanent\033[m")

    if patches.with_eac and patches.executable != "eldenring.exe":
        exit("er-patcher: --with-eac is mutually exclusive with --executable")

    if patches.gamepath[-1] == "/" or patches.gamepath[-1] == "\\":
        patches.gamepath = patches.gamepath[:len(patches.gamepath)-1]

    if os.path.exists(f"{patches.gamepath}/eldenring.exe"):
        game_dir = Path(patches.gamepath)
    elif os.path.exists("~/.local/share/Steam/steamapps/common/ELDEN RING/Game/eldenring.exe"):
        game_dir = Path("~/.local/share/Steam/steamapps/common/ELDEN RING/Game/eldenring.exe")
    elif os.path.exists("C:/Program Files/Steam/steamapps/common/ELDEN RING/Game/eldenring.exe"):
        game_dir = Path("C:/Program Files/Steam/steamapps/common/ELDEN RING/Game/eldenring.exe")
    elif os.path.exists("C:/Program Files (x86)/Steam/steamapps/common/ELDEN RING/Game/eldenring.exe"):
        game_dir = Path("C:/Program Files (x86)/Steam/steamapps/common/ELDEN RING/Game/eldenring.exe")
    else:
        exit("\033[91mCould not find eldenring.exe\033[m")

    exe_hex = open(game_dir / "eldenring.exe", "rb").read().hex()

    if hashlib.sha256(exe_hex.encode("utf-8")).hexdigest() != "cf2797fab10fbbb52f73f96e6d8d7a4fabbfb8e6a772e78bcd24aef58c8967d4":
        print("\033[91mWarning: eldenring.exe is modified, this can lead to unexpected behavior\033[m")

    if patches.fix_camera or patches.all:
        pattern = "80 .. .. .. .. .. 00 74 .. .. 8b .. e8 .. .. .. .. eb .. 0f 28 .. .. .. .. .. .. 8d".replace(" ", "")
        if (res := re.search(pattern, exe_hex)) is not None:
            addr = res.span()[0] + 14
            patch = "eb".replace(" ", "")
            orig = "74"
            if exe_hex[addr:addr + len(patch)] == orig:
                exe_hex = exe_hex[:addr] + patch + exe_hex[addr + len(patch):]
                print("\033[92m✓ er-patcher: fix camera\033[m")
            else:
                print("\033[91m✗ er-patcher: fix camera pattern does not match\033[m")
        else:
            print("\033[91m✗ er-patcher: fix camera pattern scan failed\033[m")

    if patches.no_rotate_camera:
        pattern = "0f 29 .. .. .. .. .. .. 0f 28 .. .. 8b .. e8 .. .. .. .. .. 0f b6 .. .. .. .. 0f 28 .. .. 8b .. e8 .. .. .. .. .. 8b .. .. 0f 28 .. .. 8b .. e8 .. .. .. .. .. 8d .. .. .. 8b .. .. 8d".replace(" ", "")
        if (res := re.search(pattern, exe_hex)) is not None:
            addr = res.span()[0]
            patch = "90 90 90 90 90 90 90".replace(" ", "")
            exe_hex = exe_hex[:addr] + patch + exe_hex[addr + len(patch):]
            print("\033[92m✓ er-patcher: no rotate camera\033[m")
        else:
            print("\033[91m✗ er-patcher: no rotate camera pattern scan failed\033[m")

    if patches.quick_respawn or patches.all:
        pattern = "74 .. f3 0f 10 19".replace(" ", "")
        if (res := re.search(pattern, exe_hex)) is not None:
            addr = res.span()[0]
            patch = "eb".replace(" ", "")
            exe_hex = exe_hex[:addr] + patch + exe_hex[addr + len(patch):]
            print("\033[92m✓ er-patcher: quick respawn\033[m")
        else:
            print("\033[91m✗ er-patcher: quick respawn pattern scan failed\033[m")

    if patches.player_camera:
        pattern = "66 0f 7f 07 f3 0f 10 ab".replace(" ", "")
        if (res := re.search(pattern, exe_hex)) is not None:
            addr = res.span()[0]
            patch = "90 90 90 90".replace(" ", "")
            exe_hex = exe_hex[:addr] + patch + exe_hex[addr + len(patch):]
            print("\033[92m✓ er-patcher: center camera to player\033[m")
        else:
            print("\033[91m✗ er-patcher: center camera to player pattern scan failed\033[m")

    if patches.rate != 60 and patches.rate > 0:
        pattern = "c7 43 1c 89 88 88 3c eb 6d 89 73 18 eb c7 89 73 18".replace(" ", "")
        if (res := re.search(pattern, exe_hex)) is not None:
            addr = res.span()[0] + 6
            patch = struct.pack('<f', 1 / patches.rate).hex()
            exe_hex = exe_hex[:addr] + patch + exe_hex[addr + len(patch):]
            print("\033[92m✓ er-patcher: refresh rate\033[m")
        else:
            print("\033[91m✗ er-patcher: refresh rate pattern scan failed\033[m")

    if patches.disable_rune_loss:
        pattern = "41 .. 01 48 .. .. e8 .. .. .. .. 48 .. .. .. .. 32 c0".replace(" ", "")
        if (res := re.search(pattern, exe_hex)) is not None:
            addr = res.span()[0] + 12
            patch = "90 90 90 90 90".replace(" ", "")  # NOP
            exe_hex = exe_hex[:addr] + patch + exe_hex[addr + len(patch):]
            print("\033[92m✓ er-patcher: disable rune loss\033[m")
        else:
            print("\033[91m✗ er-patcher: disable rune loss pattern scan failed\033[m")

    if patches.ultrawide or patches.all:
        pattern = "74 4f 45 8b 94 cc".replace(" ", "")
        if (res := re.search(pattern, exe_hex)) is not None:
            addr = res.span()[0]
            patch = "eb"
            exe_hex = exe_hex[:addr] + patch + exe_hex[addr + len(patch):]
            print("\033[92m✓ er-patcher: ultrawide\033[m")
        else:
            print("\033[91m✗ er-patcher: ultrawide pattern scan failed\033[m")

    if patches.disable_vignette or patches.all:
        pattern = 'f3 0f 10 .. .. f3 0f 59 .. .. .. .. .. e8 .. .. .. .. f3 41 0f .. .. f3 45 0f .. .. 4c 8d .. .. .. .. .. .. 48'.replace(" ", "")
        if (res := re.search(pattern, exe_hex)) is not None:
            addr = res.span()[0] + 46
            patch = "f3 0f 5c c0 90".replace(" ", "")  # SUBSS XMM0,XMM0; NOP;  all NOP does work too
            exe_hex = exe_hex[:addr] + patch + exe_hex[addr + len(patch):]
            print("\033[92m✓ er-patcher: disable vignette\033[m")
        else:
            print("\033[91m✗ er-patcher: disable vignette pattern scan failed\033[m")

    if patches.disable_ca or patches.all:
        pattern = "0f 11 43 60 48 8d 8b 80 00 00 00 0f 10 87 a0 00 00 00 0f 11 41 f0 48 8d 87 b0 00 00 00 0f 10 08 0f 11 09".replace(" ", "")
        if (res := re.search(pattern, exe_hex)) is not None:
            addr = res.span()[0] + 94
            orig = "0f 11 49 20".replace(" ", "")
            patch = "66 0f ef c9".replace(" ", "")  # PXOR XMM1,XMM1
            if exe_hex[addr:addr + len(patch)] == orig:
                exe_hex = exe_hex[:addr] + patch + exe_hex[addr + len(patch):]
                print("\033[92m✓ er-patcher: disable ca\033[m")
            else:
                print("\033[91m✗ er-patcher: disable ca pattern does not match\033[m")
        else:
            print("\033[91m✗ er-patcher: disable ca pattern scan failed\033[m")

    if patches.increase_animation_distance:
        pattern = "e8 .. .. .. .. 0f 28 .. 0f 28 .. e8 .. .. .. .. f3 0f .. .. 0f 28 .. f3 41 0f 5e 4c 24 54".replace(" ", "")
        if (res := re.search(pattern, exe_hex)) is not None:
            addr = res.span()[0] + 46
            patch = "0f 57 c9 66 0f ef c9".replace(" ", "")  # DIVSS XMM1,dword ptr [R12 + 0x54]  ->  XORPS XMM1,XMM1; PXOR XMM1,XMM1
            exe_hex = exe_hex[:addr] + patch + exe_hex[addr + len(patch):]
            print("\033[92m✓ er-patcher: increase animation distance\033[m")
        else:
            print("\033[91m✗ er-patcher: increase animation distance pattern scan failed\033[m")

    if patches.skip_intro or patches.all:
        pattern = "80 bf b8 00 00 00 00 74 53 48".replace(" ", "")
        if (res := re.search(pattern, exe_hex)) is not None:
            addr = res.span()[0] + 14
            patch = "90 90".replace(" ", "")
            exe_hex = exe_hex[:addr] + patch + exe_hex[addr + len(patch):]
            print("\033[92m✓ er-patcher: skip intro\033[m")
        else:
            print("\033[91m✗ er-patcher: skip intro pattern scan failed\033[m")

    if patches.remove_60hz_fullscreen or patches.all:
        pattern = "eb .. c7 .. .. 3c 00 00 00 c7 .. .. 01 00 00 00".replace(" ", "")
        if (res := re.search(pattern, exe_hex)) is not None:
            addr = res.span()[0] + 10
            patch = "00"
            exe_hex = exe_hex[:addr] + patch + exe_hex[addr + len(patch):]
            
            addr_2 = res.span()[0] + 24
            patch_2 = "00"
            exe_hex = exe_hex[:addr_2] + patch_2 + exe_hex[addr_2 + len(patch_2):]
            print("\033[92m✓ er-patcher: remove 60hz fullscreen\033[m")
        else:
            print("\033[91m✗ er-patcher: remove 60hz fullscreen pattern scan failed\033[m")

    if patches.permanent:
        if patches.with_eac:
            if os.path.exists(f"{game_dir}/eldenring.exe") and not os.path.exists(f"{game_dir}/eldenring.exe.bak"):
                copy(f"{game_dir}/eldenring.exe", f"{game_dir}/eldenring.exe.bak")
                print("eldenring.exe backuped as eldenring.exe.bak")
            else:
                exit("\033[91meldenring.exe does not exist\033[m")
            exe = f"{game_dir}/eldenring.exe"
            print("\033[93mEAC enabled, you might get banned with this patches\033[m")
        else:
            if os.path.exists(f"{game_dir}/start_protected_game.exe") and not os.path.exists(f"{game_dir}/start_protected_game.exe.bak"):
                copy(f"{game_dir}/start_protected_game.exe", f"{game_dir}/start_protected_game.exe.bak")
                print("start_protected_game.exe backuped as start_protected_game.exe.bak")
            exe = f"{game_dir}/start_protected_game.exe"
            print("\033[92mEAC disabled, you cannot go online on official servers\033[m")

        # patch elden ring
        open(exe, "wb").write(bytes.fromhex(exe_hex))
        del exe_hex

        exe = exe.replace("\\", "/")
        print(f"Patches permanently written to {os.path.join(exe)}")
    else:
        game_dir_patched = Path(f"{game_dir}/er-patcher-tmp/")

        # make sure a fresh directory is used
        cleanup(game_dir_patched)

        if not game_dir_patched.is_dir():
            game_dir_patched.mkdir()

        open(game_dir_patched / "eldenring.exe", "wb").write(bytes.fromhex(exe_hex))

        del exe_hex

        # recreate game directory tree in game_dir_patched
        game_dirs = [d for d in game_dir.rglob("*") if d.is_dir()]
        for d in game_dirs:
            if d == game_dir_patched:
                continue
            if not (game_dir_patched / d).is_dir():
                (game_dir_patched / d).mkdir(parents=True)

        # hard link game files to game_dir_patched; symbolic links would be easier
        # to handle but by default windows 10 doesn't allow them
        game_files = [f for f in game_dir.rglob("*") if f.is_file()]
        for f in game_files:
            if f.name in ["eldenring.exe", "er-patcher"]:
                continue
            if not (game_dir_patched / f).is_file():
                if sys.version_info.minor >= 10:
                    (game_dir_patched / f).hardlink_to(f)
                else:
                    f.link_to(game_dir_patched / f)
        
        if patches.with_eac:
            print("\033[93mEAC enabled, you might get banned with this patches\033[m")

        # start patched exe directly to avoid EAC
        steam_cmd = sys.argv[1 + sys.argv.index("--"):]
        steam_cmd[-1] = Path(steam_cmd[-1]).parent.absolute() / game_dir_patched / ("start_protected_game.exe" if patches.with_eac else patches.executable)
        subprocess.run(steam_cmd, cwd=steam_cmd[-1].parent.absolute())

        # try to remove game_dir_patched
        cleanup(game_dir_patched)
